#include "pll_presets.h"

const OutFreqConfig pll_out1_presets[] = {
    // Out 1 uses PLL A, which is also shared by the GPSDO FLL loop.
    // Because its VCO is locked to a constant 880  MHz (for a 10 MHz OCXO),
    // the pll_mult value is not used for Out 1.
    // NOTE: Do not use '.out_div = 4'; it requires a PLL reset,
    // which must not be performed on the main PLL.
    { .pll_mult = 0xFF, .out_div = 0,    .direct_xo = false, .label = "OFF " },
    { .pll_mult = 0xFF, .out_div = 1,    .direct_xo = true,  .label = "10-D" },
    { .pll_mult = 0xFF, .out_div = 2000, .direct_xo = false, .label = "0.44" },
    { .pll_mult = 0xFF, .out_div = 1760, .direct_xo = false, .label = "0.5 " },
    { .pll_mult = 0xFF, .out_div = 1600, .direct_xo = false, .label = "0.55" },
    { .pll_mult = 0xFF, .out_div = 1100, .direct_xo = false, .label = "0.8 " },
    { .pll_mult = 0xFF, .out_div = 1000, .direct_xo = false, .label = "0.88" },
    { .pll_mult = 0xFF, .out_div = 880,  .direct_xo = false, .label = "1   " },
    { .pll_mult = 0xFF, .out_div = 800,  .direct_xo = false, .label = "1.1 " },
    { .pll_mult = 0xFF, .out_div = 704,  .direct_xo = false, .label = "1.25" },
    { .pll_mult = 0xFF, .out_div = 550,  .direct_xo = false, .label = "1.6 " },
    { .pll_mult = 0xFF, .out_div = 500,  .direct_xo = false, .label = "1.76" },
    { .pll_mult = 0xFF, .out_div = 440,  .direct_xo = false, .label = "2   " },
    { .pll_mult = 0xFF, .out_div = 400,  .direct_xo = false, .label = "2.2 " },
    { .pll_mult = 0xFF, .out_div = 352,  .direct_xo = false, .label = "2.5 " },
    { .pll_mult = 0xFF, .out_div = 320,  .direct_xo = false, .label = "2.75" },
    { .pll_mult = 0xFF, .out_div = 250,  .direct_xo = false, .label = "3.52" },
    { .pll_mult = 0xFF, .out_div = 220,  .direct_xo = false, .label = "4   " },
    { .pll_mult = 0xFF, .out_div = 200,  .direct_xo = false, .label = "4.4 " },
    { .pll_mult = 0xFF, .out_div = 176,  .direct_xo = false, .label = "5   " },
    { .pll_mult = 0xFF, .out_div = 160,  .direct_xo = false, .label = "5.5 " },
    { .pll_mult = 0xFF, .out_div = 110,  .direct_xo = false, .label = "8   " },
    { .pll_mult = 0xFF, .out_div = 100,  .direct_xo = false, .label = "8.8 " },
    { .pll_mult = 0xFF, .out_div = 88,   .direct_xo = false, .label = "10  " },
    { .pll_mult = 0xFF, .out_div = 80,   .direct_xo = false, .label = "11  " },
    { .pll_mult = 0xFF, .out_div = 50,   .direct_xo = false, .label = "17.6" },
    { .pll_mult = 0xFF, .out_div = 44,   .direct_xo = false, .label = "20  " },
    { .pll_mult = 0xFF, .out_div = 40,   .direct_xo = false, .label = "22  " },
    { .pll_mult = 0xFF, .out_div = 32,   .direct_xo = false, .label = "27.5" },
    { .pll_mult = 0xFF, .out_div = 22,   .direct_xo = false, .label = "40  " },
    { .pll_mult = 0xFF, .out_div = 20,   .direct_xo = false, .label = "44  " },
    { .pll_mult = 0xFF, .out_div = 16,   .direct_xo = false, .label = "55  " },
    { .pll_mult = 0xFF, .out_div = 10,   .direct_xo = false, .label = "88  " },
    { .pll_mult = 0xFF, .out_div = 8,    .direct_xo = false, .label = "110 " },
};

const uint16_t pll_out1_preset_count = sizeof(pll_out1_presets) / sizeof(pll_out1_presets[0]);


const OutFreqConfig pll_out2_presets[] = {
    { .pll_mult = 60, .out_div = 0,    .direct_xo = false, .label = "OFF     " },
    { .pll_mult = 60, .out_div = 1,    .direct_xo = true,  .label = "10-DIRCT" },
    { .pll_mult = 60, .out_div = 2000, .direct_xo = false, .label = "0.3     " },
    { .pll_mult = 80, .out_div = 2000, .direct_xo = false, .label = "0.4     " },
    { .pll_mult = 90, .out_div = 1800, .direct_xo = false, .label = "0.5     " },
    { .pll_mult = 90, .out_div = 1500, .direct_xo = false, .label = "0.6     " },
    { .pll_mult = 84, .out_div = 1200, .direct_xo = false, .label = "0.7     " },
    { .pll_mult = 88, .out_div = 1100, .direct_xo = false, .label = "0.8     " },
    { .pll_mult = 90, .out_div = 1000, .direct_xo = false, .label = "0.9     " },
    { .pll_mult = 90, .out_div = 900,  .direct_xo = false, .label = "1       " },
    { .pll_mult = 88, .out_div = 800,  .direct_xo = false, .label = "1.1     " },
    { .pll_mult = 90, .out_div = 750,  .direct_xo = false, .label = "1.2     " },
    { .pll_mult = 78, .out_div = 600,  .direct_xo = false, .label = "1.3     " },
    { .pll_mult = 84, .out_div = 600,  .direct_xo = false, .label = "1.4     " },
    { .pll_mult = 90, .out_div = 600,  .direct_xo = false, .label = "1.5     " },
    { .pll_mult = 88, .out_div = 550,  .direct_xo = false, .label = "1.6     " },
    { .pll_mult = 68, .out_div = 400,  .direct_xo = false, .label = "1.7     " },
    { .pll_mult = 90, .out_div = 500,  .direct_xo = false, .label = "1.8     " },
    { .pll_mult = 76, .out_div = 400,  .direct_xo = false, .label = "1.9     " },
    { .pll_mult = 90, .out_div = 450,  .direct_xo = false, .label = "2       " },
    { .pll_mult = 84, .out_div = 400,  .direct_xo = false, .label = "2.1     " },
    { .pll_mult = 88, .out_div = 400,  .direct_xo = false, .label = "2.2     " },
    { .pll_mult = 69, .out_div = 300,  .direct_xo = false, .label = "2.3     " },
    { .pll_mult = 84, .out_div = 350,  .direct_xo = false, .label = "2.4     " },
    { .pll_mult = 90, .out_div = 360,  .direct_xo = false, .label = "2.5     " },
    { .pll_mult = 78, .out_div = 300,  .direct_xo = false, .label = "2.6     " },
    { .pll_mult = 81, .out_div = 300,  .direct_xo = false, .label = "2.7     " },
    { .pll_mult = 84, .out_div = 300,  .direct_xo = false, .label = "2.8     " },
    { .pll_mult = 87, .out_div = 300,  .direct_xo = false, .label = "2.9     " },
    { .pll_mult = 90, .out_div = 300,  .direct_xo = false, .label = "3       " },
    { .pll_mult = 62, .out_div = 200,  .direct_xo = false, .label = "3.1     " },
    { .pll_mult = 90, .out_div = 288,  .direct_xo = false, .label = "3.125   " },
    { .pll_mult = 80, .out_div = 250,  .direct_xo = false, .label = "3.2     " },
    { .pll_mult = 78, .out_div = 240,  .direct_xo = false, .label = "3.25    " },
    { .pll_mult = 66, .out_div = 200,  .direct_xo = false, .label = "3.3     " },
    { .pll_mult = 90, .out_div = 270,  .direct_xo = false, .label = "3.(3)   " },
    { .pll_mult = 68, .out_div = 200,  .direct_xo = false, .label = "3.4     " },
    { .pll_mult = 84, .out_div = 240,  .direct_xo = false, .label = "3.5     " },
    { .pll_mult = 90, .out_div = 250,  .direct_xo = false, .label = "3.6     " },
    { .pll_mult = 74, .out_div = 200,  .direct_xo = false, .label = "3.7     " },
    { .pll_mult = 76, .out_div = 200,  .direct_xo = false, .label = "3.8     " },
    { .pll_mult = 78, .out_div = 200,  .direct_xo = false, .label = "3.9     " },
    { .pll_mult = 88, .out_div = 220,  .direct_xo = false, .label = "4       " },
    { .pll_mult = 90, .out_div = 200,  .direct_xo = false, .label = "4.5     " },
    { .pll_mult = 72, .out_div = 150,  .direct_xo = false, .label = "4.8     " },
    { .pll_mult = 90, .out_div = 180,  .direct_xo = false, .label = "5       " },
    { .pll_mult = 63, .out_div = 120,  .direct_xo = false, .label = "5.25    " },
    { .pll_mult = 88, .out_div = 160,  .direct_xo = false, .label = "5.5     " },
    { .pll_mult = 69, .out_div = 120,  .direct_xo = false, .label = "5.75    " },
    { .pll_mult = 90, .out_div = 150,  .direct_xo = false, .label = "6       " },
    { .pll_mult = 90, .out_div = 144,  .direct_xo = false, .label = "6.25    " },
    { .pll_mult = 78, .out_div = 120,  .direct_xo = false, .label = "6.5     " },
    { .pll_mult = 81, .out_div = 120,  .direct_xo = false, .label = "6.75    " },
    { .pll_mult = 84, .out_div = 120,  .direct_xo = false, .label = "7       " },
    { .pll_mult = 72, .out_div = 100,  .direct_xo = false, .label = "7.2     " },
    { .pll_mult = 87, .out_div = 120,  .direct_xo = false, .label = "7.25    " },
    { .pll_mult = 90, .out_div = 120,  .direct_xo = false, .label = "7.5     " },
    { .pll_mult = 62, .out_div = 80,   .direct_xo = false, .label = "7.75    " },
    { .pll_mult = 88, .out_div = 110,  .direct_xo = false, .label = "8       " },
    { .pll_mult = 66, .out_div = 80,   .direct_xo = false, .label = "8.25    " },
    { .pll_mult = 68, .out_div = 80,   .direct_xo = false, .label = "8.5     " },
    { .pll_mult = 84, .out_div = 96,   .direct_xo = false, .label = "8.75    " },
    { .pll_mult = 90, .out_div = 100,  .direct_xo = false, .label = "9       " },
    { .pll_mult = 90, .out_div = 90,   .direct_xo = false, .label = "10      " },
    { .pll_mult = 82, .out_div = 80,   .direct_xo = false, .label = "10.25   " },
    { .pll_mult = 84, .out_div = 80,   .direct_xo = false, .label = "10.5    " },
    { .pll_mult = 88, .out_div = 80,   .direct_xo = false, .label = "11      " },
    { .pll_mult = 84, .out_div = 70,   .direct_xo = false, .label = "12      " },
    { .pll_mult = 81, .out_div = 66,   .direct_xo = false, .label = "12.(27) " },
    { .pll_mult = 90, .out_div = 72,   .direct_xo = false, .label = "12.5    " },
    { .pll_mult = 64, .out_div = 50,   .direct_xo = false, .label = "12.8    " },
    { .pll_mult = 78, .out_div = 60,   .direct_xo = false, .label = "13      " },
    { .pll_mult = 88, .out_div = 66,   .direct_xo = false, .label = "13.(3)  " },
    { .pll_mult = 81, .out_div = 60,   .direct_xo = false, .label = "13.5    " },
    { .pll_mult = 84, .out_div = 60,   .direct_xo = false, .label = "14      " },
    { .pll_mult = 63, .out_div = 44,   .direct_xo = false, .label = "14.3(18)" },
    { .pll_mult = 72, .out_div = 50,   .direct_xo = false, .label = "14.4    " },
    { .pll_mult = 87, .out_div = 60,   .direct_xo = false, .label = "14.5    " },
    { .pll_mult = 90, .out_div = 60,   .direct_xo = false, .label = "15      " },
    { .pll_mult = 80, .out_div = 50,   .direct_xo = false, .label = "16      " },
    { .pll_mult = 81, .out_div = 50,   .direct_xo = false, .label = "16.2    " },
    { .pll_mult = 66, .out_div = 40,   .direct_xo = false, .label = "16.5    " },
    { .pll_mult = 90, .out_div = 54,   .direct_xo = false, .label = "16.(6)  " },
    { .pll_mult = 84, .out_div = 50,   .direct_xo = false, .label = "16.8    " },
    { .pll_mult = 68, .out_div = 40,   .direct_xo = false, .label = "17      " },
    { .pll_mult = 84, .out_div = 48,   .direct_xo = false, .label = "17.5    " },
    { .pll_mult = 90, .out_div = 50,   .direct_xo = false, .label = "18      " },
    { .pll_mult = 76, .out_div = 40,   .direct_xo = false, .label = "19      " },
    { .pll_mult = 88, .out_div = 44,   .direct_xo = false, .label = "20      " },
    { .pll_mult = 84, .out_div = 40,   .direct_xo = false, .label = "21      " },
    { .pll_mult = 68, .out_div = 32,   .direct_xo = false, .label = "21.25   " },
    { .pll_mult = 88, .out_div = 40,   .direct_xo = false, .label = "22      " },
    { .pll_mult = 69, .out_div = 30,   .direct_xo = false, .label = "23      " },
    { .pll_mult = 72, .out_div = 30,   .direct_xo = false, .label = "24      " },
    { .pll_mult = 90, .out_div = 36,   .direct_xo = false, .label = "25      " },
    { .pll_mult = 78, .out_div = 30,   .direct_xo = false, .label = "26      " },
    { .pll_mult = 81, .out_div = 30,   .direct_xo = false, .label = "27      " },
    { .pll_mult = 88, .out_div = 32,   .direct_xo = false, .label = "27.5    " },
    { .pll_mult = 84, .out_div = 30,   .direct_xo = false, .label = "28      " },
    { .pll_mult = 63, .out_div = 22,   .direct_xo = false, .label = "28.(63) " },
    { .pll_mult = 87, .out_div = 30,   .direct_xo = false, .label = "29      " },
    { .pll_mult = 90, .out_div = 30,   .direct_xo = false, .label = "30      " },
    { .pll_mult = 62, .out_div = 20,   .direct_xo = false, .label = "31      " },
    { .pll_mult = 75, .out_div = 24,   .direct_xo = false, .label = "31.25   " },
    { .pll_mult = 64, .out_div = 20,   .direct_xo = false, .label = "32      " },
    { .pll_mult = 77, .out_div = 24,   .direct_xo = false, .label = "32.08(3)" },
    { .pll_mult = 66, .out_div = 20,   .direct_xo = false, .label = "33      " },
    { .pll_mult = 80, .out_div = 24,   .direct_xo = false, .label = "33.(3)  " },
    { .pll_mult = 68, .out_div = 20,   .direct_xo = false, .label = "34      " },
    { .pll_mult = 84, .out_div = 24,   .direct_xo = false, .label = "35      " },
    { .pll_mult = 72, .out_div = 20,   .direct_xo = false, .label = "36      " },
    { .pll_mult = 74, .out_div = 20,   .direct_xo = false, .label = "37      " },
    { .pll_mult = 90, .out_div = 24,   .direct_xo = false, .label = "37.5    " },
    { .pll_mult = 76, .out_div = 20,   .direct_xo = false, .label = "38      " },
    { .pll_mult = 78, .out_div = 20,   .direct_xo = false, .label = "39      " },
    { .pll_mult = 88, .out_div = 22,   .direct_xo = false, .label = "40      " },
    { .pll_mult = 81, .out_div = 20,   .direct_xo = false, .label = "40.5    " },
    { .pll_mult = 82, .out_div = 20,   .direct_xo = false, .label = "41      " },
    { .pll_mult = 83, .out_div = 20,   .direct_xo = false, .label = "41.5    " },
    { .pll_mult = 75, .out_div = 18,   .direct_xo = false, .label = "41.(6)  " },
    { .pll_mult = 84, .out_div = 20,   .direct_xo = false, .label = "42      " },
    { .pll_mult = 68, .out_div = 16,   .direct_xo = false, .label = "42.5    " },
    { .pll_mult = 86, .out_div = 20,   .direct_xo = false, .label = "43      " },
    { .pll_mult = 88, .out_div = 20,   .direct_xo = false, .label = "44      " },
    { .pll_mult = 90, .out_div = 20,   .direct_xo = false, .label = "45      " },
    { .pll_mult = 78, .out_div = 16,   .direct_xo = false, .label = "48.75   " },
    { .pll_mult = 90, .out_div = 18,   .direct_xo = false, .label = "50      " },
    { .pll_mult = 81, .out_div = 16,   .direct_xo = false, .label = "50.625  " },
    { .pll_mult = 88, .out_div = 16,   .direct_xo = false, .label = "55      " },
    { .pll_mult = 84, .out_div = 14,   .direct_xo = false, .label = "60      " },
    { .pll_mult = 61, .out_div = 10,   .direct_xo = false, .label = "61      " },
    { .pll_mult = 62, .out_div = 10,   .direct_xo = false, .label = "62      " },
    { .pll_mult = 75, .out_div = 12,   .direct_xo = false, .label = "62.5    " },
    { .pll_mult = 63, .out_div = 10,   .direct_xo = false, .label = "63      " },
    { .pll_mult = 64, .out_div = 10,   .direct_xo = false, .label = "64      " },
    { .pll_mult = 78, .out_div = 12,   .direct_xo = false, .label = "65      " },
    { .pll_mult = 66, .out_div = 10,   .direct_xo = false, .label = "66      " },
    { .pll_mult = 80, .out_div = 12,   .direct_xo = false, .label = "66.(6)  " },
    { .pll_mult = 67, .out_div = 10,   .direct_xo = false, .label = "67      " },
    { .pll_mult = 81, .out_div = 12,   .direct_xo = false, .label = "67.5    " },
    { .pll_mult = 68, .out_div = 10,   .direct_xo = false, .label = "68      " },
    { .pll_mult = 69, .out_div = 10,   .direct_xo = false, .label = "69      " },
    { .pll_mult = 84, .out_div = 12,   .direct_xo = false, .label = "70      " },
    { .pll_mult = 71, .out_div = 10,   .direct_xo = false, .label = "71      " },
    { .pll_mult = 72, .out_div = 10,   .direct_xo = false, .label = "72      " },
    { .pll_mult = 73, .out_div = 10,   .direct_xo = false, .label = "73      " },
    { .pll_mult = 74, .out_div = 10,   .direct_xo = false, .label = "74      " },
    { .pll_mult = 90, .out_div = 12,   .direct_xo = false, .label = "75      " },
    { .pll_mult = 76, .out_div = 10,   .direct_xo = false, .label = "76      " },
    { .pll_mult = 77, .out_div = 10,   .direct_xo = false, .label = "77      " },
    { .pll_mult = 78, .out_div = 10,   .direct_xo = false, .label = "78      " },
    { .pll_mult = 79, .out_div = 10,   .direct_xo = false, .label = "79      " },
    { .pll_mult = 80, .out_div = 10,   .direct_xo = false, .label = "80      " },
    { .pll_mult = 81, .out_div = 10,   .direct_xo = false, .label = "81      " },
    { .pll_mult = 82, .out_div = 10,   .direct_xo = false, .label = "82      " },
    { .pll_mult = 83, .out_div = 10,   .direct_xo = false, .label = "83      " },
    { .pll_mult = 84, .out_div = 10,   .direct_xo = false, .label = "84      " },
    { .pll_mult = 85, .out_div = 10,   .direct_xo = false, .label = "85      " },
    { .pll_mult = 86, .out_div = 10,   .direct_xo = false, .label = "86      " },
    { .pll_mult = 87, .out_div = 10,   .direct_xo = false, .label = "87      " },
    { .pll_mult = 88, .out_div = 10,   .direct_xo = false, .label = "88      " },
    { .pll_mult = 89, .out_div = 10,   .direct_xo = false, .label = "89      " },
    { .pll_mult = 90, .out_div = 10,   .direct_xo = false, .label = "90      " },
    { .pll_mult = 76, .out_div = 8,    .direct_xo = false, .label = "95      " },
    { .pll_mult = 80, .out_div = 8,    .direct_xo = false, .label = "100     " },
    { .pll_mult = 84, .out_div = 8,    .direct_xo = false, .label = "105     " },
    { .pll_mult = 85, .out_div = 8,    .direct_xo = false, .label = "106.25  " },
    { .pll_mult = 88, .out_div = 8,    .direct_xo = false, .label = "110     " },
    { .pll_mult = 69, .out_div = 6,    .direct_xo = false, .label = "115     " },
    { .pll_mult = 72, .out_div = 6,    .direct_xo = false, .label = "120     " },
    { .pll_mult = 60, .out_div = 4,    .direct_xo = false, .label = "150     " },
    { .pll_mult = 62, .out_div = 4,    .direct_xo = false, .label = "155     " },
    { .pll_mult = 64, .out_div = 4,    .direct_xo = false, .label = "160     " },
    { .pll_mult = 66, .out_div = 4,    .direct_xo = false, .label = "165     " },
    { .pll_mult = 68, .out_div = 4,    .direct_xo = false, .label = "170     " },
    { .pll_mult = 70, .out_div = 4,    .direct_xo = false, .label = "175     " },
    { .pll_mult = 72, .out_div = 4,    .direct_xo = false, .label = "180     " },
    { .pll_mult = 74, .out_div = 4,    .direct_xo = false, .label = "185     " },
    { .pll_mult = 76, .out_div = 4,    .direct_xo = false, .label = "190     " },
    { .pll_mult = 78, .out_div = 4,    .direct_xo = false, .label = "195     " },
    { .pll_mult = 80, .out_div = 4,    .direct_xo = false, .label = "200     " },
};

const uint16_t pll_out2_preset_count = sizeof(pll_out2_presets) / sizeof(pll_out2_presets[0]);
